meta:
  id: retina-rag-pipeline
  version: "1.0.0"

log:
  level: DEBUG

redis:
  host: localhost
  port: 6379
  db: 0
  url: redis://localhost:6379/0

celery:
  broker_url: redis://localhost:6379/0
  result_backend: redis://localhost:6379/0

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "documents"
  secure: false

api:
  host: 0.0.0.0
  port: 8000
  title: "Retina RAG Pipeline API"
  debug: true

# Qdrant vector database configuration
qdrant:
  url: "http://localhost:6333"
  index: "retina_documents"
  embedding_dim: 384  # dimension for sentence-transformers/all-MiniLM-L6-v2
  recreate_index: false
  return_embedding: true
  wait_result_from_api: true
  auto_create_collection: false  # Disable automatic collection creation

# Multi-tenancy configuration
tenancy:
  organization_prefix: "org"  # Prefix for organization-specific resources (collections, buckets)

# Haystack (indexing & retrieval) pipeline configuration
haystack:
  embedder:
    model: "sentence-transformers/all-MiniLM-L6-v2"
    progress_bar: false
  splitter:
    split_by: "word"
    split_length: 200
    split_overlap: 50
  cleaner:
    remove_empty_lines: true
    remove_extra_whitespaces: true
    remove_repeated_substrings: false

# LLM configuration for query pipeline
llm:
  model: "llama3.2"  # Ollama model name (e.g., llama3.2, mistral, codellama)
  base_url: "http://localhost:11434"  # Ollama server URL

# Database configuration for SQL queries
database:
  connection_string: "test.db"  # SQLite database path
  schema: |
    CREATE TABLE users (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      age INTEGER,
      email TEXT,
      city TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE orders (
      id INTEGER PRIMARY KEY,
      user_id INTEGER,
      product_name TEXT,
      amount DECIMAL(10,2),
      order_date DATE,
      FOREIGN KEY (user_id) REFERENCES users(id)
    );
    
    CREATE TABLE products (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      price DECIMAL(10,2),
      category TEXT,
      in_stock BOOLEAN
    );

# Query pipeline configuration
query:
  retriever:
    top_k: 1  # Number of documents to retrieve for each query