version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # celery_worker:
  #   build: .
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  #   command: celery -A app.workers.ingestion_tasks.celery_app worker --loglevel=info --concurrency=4
  #   healthcheck:
  #     test: ["CMD", "celery", "-A", "app.workers.ingestion_tasks.celery_app", "inspect", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # celery_flower:
  #   build: .
  #   ports:
  #     - "5555:5555"
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  #   command: celery -A app.workers.ingestion_tasks.celery_app flower --port=5555
  #   profiles: ["monitoring"]

volumes:
  redis_data:
